<?php

namespace Uzulla;

use Doctrine\ORM\EntityRepository;

/**
 * Book
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Book extends EntityRepository
{
    public function ucTitle(){
        return strtoupper($this->getTitle());
    }

}
